# Color scheme
import = ["/home/alvin/.config/alacritty/one_dark.toml"]

[shell]
program = "/usr/bin/fish"

[env]
TERM = "alacritty"

[window]
padding = { x = 2, y = 2 }
dynamic_padding = true
opacity = 0.8
blur = true

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
size = 11

# [cursor.style]
# shape = "Underline"
# blinking = "On"
