format = """\
[╭╴](238)$time$battery$env_var\
$all[╰─](238)$character"""

add_newline = true

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "

[[battery.display]]
threshold = 30
style = "bold red"

[[battery.display]]
threshold = 75
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

[c]
symbol = " "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[cmd_duration]
min_time = 1_000
show_milliseconds = false
format = "took [$duration]($style)"
show_notifications = false

[directory]
truncation_length = 3
read_only = " 󰌾"

[direnv]
disabled = false

[docker_context]
symbol = " "
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile", "compose.yaml"]

[git_branch]
symbol = " "

[git_metrics]
disabled = true

[hostname]
ssh_only = true

[java]
symbol = " "

[memory_usage]
threshold = 70
format = "$symbol[$ram]($style)"
symbol = "󰍛 "
disabled = false

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "
python_binary = ["./venv/bin/python", "python"]

[rust]
symbol = " "

[status]
disabled = true

[sudo]
disabled = true
allow_windows = false

[time]
format = '[\[$time\]]($style)'
disabled = false

[username]
show_always = false

[custom.files]
description = "Show files count for current directory"
command = "find ./ -maxdepth 1 -type f | wc -l"
format = "📝[$output]($style) "
style = "white"
when = "true"
disabled = true

[custom.directories]
description = "Show directory count count for current directory"
command = "find ./ -maxdepth 1 -type d | tail -n +2 | wc -l"
format = "📁[$output]($style) "
style = "blue"
when = "true"
disabled = true
