local opt = vim.opt

opt.tabstop = 4
opt.softtabstop = 0
opt.shiftwidth = 4
opt.expandtab = true
opt.number = true
opt.relativenumber = true
opt.hidden = true
opt.wrap = false
opt.completeopt = "menu,menuone,noselect"
opt.wildmenu = true
opt.confirm = true
opt.cursorline = true
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.smartindent = true
opt.termguicolors = true
opt.ignorecase = true
opt.mouse = "a"
opt.list = true
opt.listchars = {
    tab = "  ",
    multispace = "·",
    lead = "·",
    leadmultispace = "·",
    trail = "·",
    extends = "›",
    precedes = "‹",
    nbsp = "·",
}
opt.incsearch = true
opt.updatetime = 200
opt.hlsearch = true
opt.clipboard = "unnamedplus"
opt.splitright = true
opt.splitbelow = true
opt.inccommand = "nosplit"
opt.signcolumn = "yes"
opt.smartcase = true
opt.undofile = true
