#!/bin/sh

notification=$(dunstctl is-paused)

if $notification
then
    dunstctl set-paused toggle
    dunstify -a "NOTIFICATION" "Notifications enabled" -u normal
else
    dunstify -a "NOTIFICATION" "Notifications disabled" -u normal
    sleep 6
    dunstctl set-paused toggle
fi
