#!/bin/sh

up() {
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
    volumestring=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
    volumefloat=${volumestring:8:4}
    volume=$(echo "$volumefloat * 100" | bc)
    [ $volume -lt 100 ] && volume=`expr $volume`  
    dunstify -a "VOLUME" "Increasing to $volume%" -h int:value:"$volume" -i audio-volume-high-symbolic -r 2593 -u normal
}

down() {
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
    volumestring=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
    volumefloat=${volumestring:8:4}
    volume=$(echo "$volumefloat * 100" | bc)
    [$volume -gt 0 ] && volume=`expr $volume`  
    dunstify -a "VOLUME" "Decreasing to $volume%" -h int:value:"$volume" -i audio-volume-low-symbolic -r 2593 -u normal
}

mute() {
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    muted=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
    if [[ $muted =~ "MUTED" ]]; then
        dunstify -a "VOLUME" "MUTED" -i audio-volume-muted-symbolic -r 2593 -u normal
    else
        dunstify -a "VOLUME" "UNMUTED" -i audio-volume-high-symbolic -r 2593 -u normal
    fi
}

case "$1" in
    up) up;;
    down) down;;
    mute) mute;;
esac
