#!/bin/bash

monitor=(`hyprctl monitors |  grep Monitor | awk '{print $2}'`)
wallpaper_directory=~/.config/wallpaper/dark
wal=$(find ${wallpaper_directory} -name '*' | tail -n +2 | shuf -n 1)
cache=""

sleep 3

while true; do
    if [[ $cache == $wal ]]; then
        wal=$(find ${wallpaper_directory} -name '*' | tail -n +2 | shuf -n 1)
    else
        cache=$wal
        hyprctl hyprpaper unload all
        hyprctl hyprpaper preload $wal
        for m in ''${monitor[@]}; do
            hyprctl hyprpaper wallpaper "$m,$wal"
        done

        sleep 300
    fi
done
