#!/bin/sh

export SWWW_TRANSITION_TYPE=simple
export SWWW_TRANSITION_STEP=40
export SWWW_TRANSITION_DURATION=3
export SWWW_TRANSITION_FPS=60

if ! pgrep -x "swww" >/dev/null; then
    swww init
    sleep 2
fi

swww img $HOME/.config/wallpaper/wallhaven-k7787d.jpg
